config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  get "team" => "pages#team"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, only: [:index, :new, :create, :destroy, :edit, :update, :show]
  resources :doctors, only: [:index, :show]
  resources :upvotes, only: [:create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :destroy, Comment, :user_id => user.id
      can :update, Comment, :user_id => user.id
      can :read, Comment
      can :manage, Doctor
      can :create, Comment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_attachment :photo
  belongs_to :user
  belongs_to :doctor
  has_many :upvotes
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :users
  has_many :comments
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates :user, uniqueness: {scope: :comment}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :upvotes
  belongs_to :doctor
  has_attachment :avatar

  ROLES = %i[admin doctor patient]
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
  end
  def admin?
    self.role == "admin"
  end
  def voted_for?(comment)
    comment.upvotes.where(user: self).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_comment, only: [:edit, :update, :destroy, :show]
  load_and_authorize_resource
  def index
    if params[:doctor_id]
      @comments = Comment.where(doctor_id: params[:doctor_id])
    else
      @comments=Comment.all
    end
  end
  def show
  end
  def new
    @comment=Comment.new
  end
  def create
    @comment=Comment.new(comment_params)
    @comment.user=current_user
    @comment.save
    if @comment.save
      redirect_to comments_path
    else
     render :new
    end
  end
  def destroy
    @comment.destroy
    redirect_to comments_path
  end
  def edit
  end
  def update
    if @comment.update(comment_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :doctor_id, :photo)
  end
  def find_comment
    @comment=Comment.find(params[:id])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_comment, only: [:show]
  load_and_authorize_resource
  def index
    @doctor=Doctor.all
  end
  def show
    @comment=Comment.where(doctor: @doctor).first
  end
  private
  def find_comment
    @doctor=Doctor.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    @comment=Comment.find(params[:comment_id])
    @comment.upvotes.create! user: current_user

    respond_to do |format|
      format.html { redirect_to comment_path }
      format.js
    end

  end
  def destroy
    upvote=Upvote.find(params[:id])
    @comment=upvote.comment
    upvote.destroy
    respond_to do |format|
      format.html { redirect_to comment_path }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for @comment do |f| %>
  <%= f.input :text, placeholder: "My opinion", label: "What is your opinion?" %>
  <%= f.input :doctor_id, placeholder: "doctor", label: "What is your doctor?" %>
  <%= f.button :submit, 'Submit', class: "btn btn-primary" %>
  <%= f.input :photo, as: :attachinary %>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <div class="row">
    <div class ="col-xs-12.col-sm-6.col-sm-offset-3">
      <h1 class="text-center">Modify a comment</h1>
      <%= render "form" %>

    </div>
  </div>
</div>

app/views/comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-center">all products</h1>
      <%= link_to "New", new_comment_path, class: "btn btn-primary btn-lg" %>
      <%= @doctors.first.id %>
      <% @comments.each do |comment| %>
        <div class="product">

          <div class="upvote-container" id="comment-<%= comment.id %>">
            <%= render 'upvotes/show', comment: comment %>
          </div>
          <% if comment.photo %>
            <%= cl_image_tag(comment.photo.path, height: 117, width: 175, crop: :fill, class: "product-image") %>

          <% else %>
            <img src="http://unsplash.it/300/200" alt="kudoz" class="product-image hidden-xs">
          <% end %>
          <div class='product-body'>
            <h3><%= comment.text %></h3>
            <p>User <%= comment.user_id %></p>
            <p>Doctor <%= comment.doctor_id %></p>
          </div>
          <ul class="list-inline product-controls hidden-sm hidden-xs">
            <li>
              <%= link_to comment_path(comment) do %>
                <i class="fa fa-eye"></i>
              <% end %>
            </li>
            <li>
              <% if can? :update, comment %>
                <%= link_to comment_path(comment), method: :delete do %>
                  <i class="fa fa-trash"></i>
                <% end %>
              <% end %>
            </li>
            <li>
              <% if can? :update, comment %>
                <%= link_to edit_comment_path(comment) do %>
                  <i class="fa fa-pencil"></i>
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<%= simple_form_for @comment do |f| %>
  <%= f.input :text, placeholder: "My opinion", label: "What is your opinion?" %>
  <%= f.input :user_id, placeholder: "user", label: "What is your user?" %>
  <%= f.input :doctor_id, placeholder: "doctor", label: "What is your doctor?" %>
  <%= f.button :submit, 'Submit', class: "btn btn-primary" %>
<% end %>

app/views/comments/show.html.erb
<h2><%= @comment.text %></h2>
<h2><%= @comment.doctor_id %></h2>
<h2><%= @comment.user_id %></h2>
<% if @comment.photo? %>
  <%= cl_image_tag @comment.photo.path, width: 200 %>
<% end %>

app/views/doctors/index.html.erb
<% @doctors.each do |doctor| %>
  <h3><%= doctor.id %></h3>
<% end %>

app/views/doctors/show.html.erb
<h2><%= @doctor.id %></h2>
<h2><%= @doctor.specialty %></h2>
<h2><%= @comment.text %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "background_home.jpg" %>');">
  <div class="banner-content">
    <h1>Zendi</h1>
    <p>Book your medical appointment</p>
    <%= link_to "All comments", comments_path, class: "btn btn-primary btn-lg" %>
    <a class="btn btn-primary btn-lg">GET IT</a>
    <%= link_to "sign-in", new_user_session_path %>
    <%= link_to "sign-up", new_user_registration_path %>
    <%= link_to "log out", destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/pages/team.html.erb
<div class="container text-center">
  <h1>Meet the team</h1>
  <%= cl_image_tag "jftvqu5bfjzsxsuyg4by", height: 200 %>


</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Text link -->
<!--     <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a> -->


    <!-- Text link -->
    <%= link_to "All comments", comments_path, class:"navbar-wagon-item navbar-wagon-link" %>

    <!-- Notification link-->
<!--     <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    </a> -->

    <!-- Profile picture and dropdown -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.avatar? %>
          <%= cl_image_tag(current_user.avatar.path, width: 30, height: 30, crop: :fill, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', :'data-toggle' => "dropdown") %>
        <% else %>
          <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
    <% end %>

    <!-- Button (call-to-action) -->
    <a href="" class="navbar-wagon-item navbar-wagon-button btn">Post stuff</a>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/upvotes/_show.html.erb
<% if user_signed_in? %>
  <% if current_user.voted_for?(comment) %>
    <%= link_to upvote_path(current_user.upvotes.where(comment: comment).first), remote: true, method: :delete, class: 'product-upvote product-upvoted' do %>
      <div class="product-arrow"></div>
      <div class="product-count"><%= comment.upvotes.size %></div>
    <% end %>
  <% else %>
    <%= link_to upvotes_path(comment_id: comment.id), remote: true, method: :post, class: 'product-upvote' do %>
      <div class="product-arrow"></div>
      <div class="product-count"><%= comment.upvotes.size %></div>
    <% end %>
  <% end %>

<% else %>
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class="product-count"><%= comment.upvotes.size %></div>
  </div>
<% end %>

app/views/upvotes/create.js.erb
$('#comment-<%= @comment.id %>').html('<%= j render 'upvotes/show', comment: @comment %>');

app/views/upvotes/destroy.js.erb
$('#comment-<%= @comment.id %>').html('<%= j render 'upvotes/show', comment: @comment %>');